require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'

Style/DoubleNegation:
  Enabled: no

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: no

Rails/InverseOf:
  Enabled: no

Style/Documentation:
  Enabled: no

RSpec/Rails/InferredSpecType:
  Enabled: no

Rails/BulkChangeTable:
  Enabled: no

RSpec/NamedSubject:
  Enabled: no

RSpec/AnyInstance:
  Enabled: no

RSpec/ContextWording:
  Enabled: no

Metrics/AbcSize:
  Enabled: yes
  Max: 50

Metrics/MethodLength:
  Enabled: yes
  Max: 150

Naming/VariableNumber:
  Enabled: no

Metrics/CyclomaticComplexity:
  Enabled: yes
  Max: 25

Metrics/PerceivedComplexity:
  Enabled: yes
  Max: 25

Metrics/ClassLength:
  Enabled: yes

Naming/AccessorMethodName:
  Enabled: yes

Layout/LineLength:
  Max: 200

RSpec/MultipleExpectations:
  Max: 11

Metrics/BlockLength:
  Enabled: true
  Max: 200

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/LetSetup:
  Enabled: no

RSpec/MessageSpies:
  Enabled: no

Rails/SkipsModelValidations:
  Enabled: no

RSpec/MessageChain:
  Enabled: no
  
RSpec/ExpectInHook:
  Enabled: no

RSpec/ExampleLength:
  Enabled: no

Lint/SymbolConversion:
  Enabled: no

Rails/CreateTableWithTimestamps:
  Enabled: no

Rails/I18nLocaleTexts:
  Enabled: no

RSpec/VerifiedDoubles:
  Enabled: false
