name: CI

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install bundler
        run: gem install bundler
      - name: Install gems
        run: bundle install --jobs 4 --retry 3
      - name: Run Tests
        run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Install rubocop
        run: gem install rubocop
      - name: Install rubocop-rails
        run: gem install rubocop-rails
      - name: Install rubocop-rspec
        run: gem install rubocop-rspec
      - name: Run rubocop
        run: rubocop
